# Generated by Django 2.1.2 on 2018-10-23 19:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('login_registration', '0003_auto_20181016_2026'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bottom',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('imageURL', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('bottom_added_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='combo_bottom_added_by', to='login_registration.User')),
            ],
        ),
        migrations.CreateModel(
            name='Combo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('bottom_chosen', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='combo_bottom', to='rotation_app.Bottom')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='combo_by', to='login_registration.User')),
            ],
        ),
        migrations.CreateModel(
            name='Schedule',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_scheduled', models.DateTimeField(auto_now_add=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Top',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('imageURL', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('top_added_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='combo_top_added_by', to='login_registration.User')),
            ],
        ),
        migrations.AddField(
            model_name='schedule',
            name='combo_chosen',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='chosen_combo', to='rotation_app.Top'),
        ),
        migrations.AddField(
            model_name='schedule',
            name='scheduled_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='combo_scheduled_by', to='login_registration.User'),
        ),
        migrations.AddField(
            model_name='combo',
            name='top_chosen',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='combo_top', to='rotation_app.Top'),
        ),
    ]
