# Generated by Django 2.1.2 on 2018-10-24 17:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rotation_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bottom',
            name='imageURL',
            field=models.CharField(max_length=1024),
        ),
        migrations.AlterField(
            model_name='schedule',
            name='date_scheduled',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='top',
            name='imageURL',
            field=models.CharField(max_length=1024),
        ),
    ]
