# Generated by Django 2.1.2 on 2018-10-25 15:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rotation_app', '0002_auto_20181024_1808'),
        ('rotation_app', '0002_auto_20181024_1715'),
    ]

    operations = [
    ]
