# Generated by Django 2.1.2 on 2018-10-25 19:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rotation_app', '0003_merge_20181025_1510'),
    ]

    operations = [
        migrations.AlterField(
            model_name='schedule',
            name='combo_chosen',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='chosen_combo', to='rotation_app.Combo'),
        ),
    ]
